#!/bin/sh
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # DEFAULT KEYS / VARIABLES / WORKSPACES / DISPLAY / KEYBOARD / LOCKSCREEN # #
set $MOD Mod4
set $ALT Mod1
set $CTRL Control
set $SHFT Shift
set $FW for_window
set $WSP workspace
set $EXC exec --no-startup-id
set $EXCA exec_always --no-startup-id
set $MVTO move container to
set $RSZ resize set
set $MVC move position center
set $FLOAT floating enable

set $MSG i3-msg
set $BAR polybar
set $BIND bindsym
set $WDUNST exec --no-startup-id dunstify -r 33 -t 600
set $ADUNST dunstify -r 33 -t 1500
set $CONFIG "${XDG_CONFIG_HOME:-$HOME/.config}"
set $TXTE lite-xl
set $COMP fastcompmgr
set $WARN notify-send -u critical

# Dependency check
$EXCA sleep 2 && which $BAR $MSG $TXTE $COMP i3lock dunstify rofi xss-lock \
feh xdotool killall || $WARN 'i3 Config WARNING!' 'MISSING DEPENDENCY!'

set $WS1 WorkSpace "1"
set $WS2 WorkSpace "2"
set $WS3 WorkSpace "3"
set $WS4 WorkSpace "4"
set $WS5 WorkSpace "5"
set $WS6 WorkSpace "6"
set $WS7 WorkSpace "7"
set $WS8 WorkSpace "8"
set $WS9 WorkSpace "9"
set $WS10 WorkSpace "10"
set $WS11 WorkSpace "11:GAME"
set $WS12 WorkSpace "12:*"


set $D1 DisplayPort-0
set $D2 DisplayPort-1
set $D3 DisplayPort-2

$WS1 output $D1
$WS2 output $D2
$WS3 output $D3
$WS4 output $D1
$WS5 output $D2
$WS6 output $D3
$WS7 output $D1
$WS8 output $D2
$WS9 output $D3
$WS11 output $D2
$WS12 output $D3

$EXCA setxkbmap -layout us,latam -option 'grp:alt_shift_toggle' # Set kb layout
$EXCA sleep 1 && xset dpms 0 0 300 &
$EXCA screenlayout && fehbg &
$EXCA $COMP &
$EXC sleep 2 && pactl set-sink-volume @DEFAULT_SINK@ 65%
$EXC xss-lock --transfer-sleep-lock -- i3lock -c 04090e --nofork --clock \
--time-color='#fdbc4b' --date-color='#FFFFFF' --inside-color='#0e1f30' \
--time-str="%l:%M %p" --date-str="%A %d/%m/%y"
$EXC xdotool key Num_Lock &

$BIND $MOD+$SHFT+equal $EXC "xrandr --setmonitor extended auto $D1,$D2,$D3 \
&& killall $BAR && $BAR main"
$BIND $MOD+equal $EXC xrandr --delmonitor extended && killall $BAR \
&& sleep 0.1 && $BAR main | $BAR work1 | $BAR work3

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # COLORS / FONT / GAPS / BORDERS /  # # # # # # # # # # # # #
# class                     border  backgr   text  indicator child_border
client.focused             #fdbc4b #091f2e #fdbc4b  #A54242   #fdbc4b
client.unfocused           #707880 #091f2e #d4d9d6  #707880   #091f2e
client.focused_inactive    #707880 #091f2e #d4d9d6  #707880   #091f2e
font pango:Nimbus Sans Bold 8.5
gaps inner 6
gaps outer 0
smart_gaps off
default_border pixel 1
default_floating_border pixel 1
mouse_warping output
focus_follows_mouse no
focus_on_window_activation focus
$FW [urgent="latest"] focus


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # SWITCH TO WORKSPACES  # # # # # # # # # # # # # # #
$BIND $MOD+1 $WS1, $WDUNST "$WS1"
$BIND $MOD+2 $WS2, $WDUNST "$WS2"
$BIND $MOD+3 $WS3, $WDUNST "$WS3"
$BIND $MOD+4 $WS4, $WDUNST "$WS4"
$BIND $MOD+5 $WS5, $WDUNST "$WS5"
$BIND $MOD+6 $WS6, $WDUNST "$WS6"
$BIND $MOD+7 $WS7, $WDUNST "$WS7"
$BIND $MOD+8 $WS8, $WDUNST "$WS8"
$BIND $MOD+9 $WS9, $WDUNST "$WS9"
$BIND $MOD+0 $WS10, $WDUNST "$WS10"

$BIND $MOD+mod2+KP_1 $WS1, $WDUNST "$WS1"
$BIND $MOD+mod2+KP_2 $WS2, $WDUNST "$WS2"
$BIND $MOD+mod2+KP_3 $WS3, $WDUNST "$WS3"
$BIND $MOD+mod2+KP_4 $WS4, $WDUNST "$WS4"
$BIND $MOD+mod2+KP_5 $WS5, $WDUNST "$WS5"
$BIND $MOD+mod2+KP_6 $WS6, $WDUNST "$WS6"
$BIND $MOD+mod2+KP_7 $WS7, $WDUNST "$WS7"
$BIND $MOD+mod2+KP_8 $WS8, $WDUNST "$WS8"
$BIND $MOD+mod2+KP_9 $WS9, $WDUNST "$WS9"
$BIND $MOD+mod2+KP_0 $WS10, $WDUNST "$WS10"
$BIND $MOD+mod2+KP_Divide $WS11, $WDUNST "$WS11"
$BIND $MOD+mod2+KP_Multiply $WS12, $WDUNST "$WS12"

$BIND $MOD+$SHFT+Left move left 360 px
$BIND $MOD+$SHFT+Down move down 245 px
$BIND $MOD+$SHFT+Up move up 245 px
$BIND $MOD+$SHFT+Right move right 360 px

$BIND $MOD+$SHFT+s move left 360 px
$BIND $MOD+$SHFT+d move down 245 px
$BIND $MOD+$SHFT+e move up 245 px
$BIND $MOD+$SHFT+f move right 360 px

$BIND $MOD+$SHFT+h move left 360 px
$BIND $MOD+$SHFT+j move down 245 px
$BIND $MOD+$SHFT+k move up 245 px
$BIND $MOD+$SHFT+l move right 360 px

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # MOVE FOCUS KEYS # # # # # # # # # # # # # # # # # #
$BIND $MOD+Left focus left
$BIND $MOD+Down focus down
$BIND $MOD+Up focus up
$BIND $MOD+Right focus right

$BIND $MOD+s focus left
$BIND $MOD+d focus down
$BIND $MOD+e focus up
$BIND $MOD+f focus right

$BIND $MOD+h focus left
$BIND $MOD+j focus down
$BIND $MOD+k focus up
$BIND $MOD+l focus right

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # RESIZE WINDOW # # # # # # # # # # # # # # # # # #
$BIND $MOD+$CTRL+Left resize shrink width 100 px or 15 ppt
$BIND $MOD+$CTRL+Down resize shrink height 100 px or 15 ppt
$BIND $MOD+$CTRL+Up resize grow height 100 px or 15 ppt
$BIND $MOD+$CTRL+Right resize grow width 100 px or 15 ppt

$BIND $MOD+$CTRL+s resize shrink width 100 px or 15 ppt
$BIND $MOD+$CTRL+d resize shrink height 100 px or 15 ppt
$BIND $MOD+$CTRL+e resize grow height 100 px or 15 ppt
$BIND $MOD+$CTRL+f resize grow width 100 px or 15 ppt

$BIND $MOD+$CTRL+h resize shrink width 100 px or 15 ppt
$BIND $MOD+$CTRL+j resize shrink height 100 px or 15 ppt
$BIND $MOD+$CTRL+k resize grow height 100 px or 15 ppt
$BIND $MOD+$CTRL+l resize grow width 100 px or 15 ppt

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # MOVE WINDOW TO WORKSPACE/MONITOR  # # # # # # # # # # # #
$BIND $MOD+$SHFT+1 $MVTO $WS1, $WS1, $WDUNST "$WS1"
$BIND $MOD+$SHFT+2 $MVTO $WS2, $WS2, $WDUNST "$WS2"
$BIND $MOD+$SHFT+3 $MVTO $WS3, $WS3, $WDUNST "$WS3"
$BIND $MOD+$SHFT+4 $MVTO $WS4, $WS4, $WDUNST "$WS4"
$BIND $MOD+$SHFT+5 $MVTO $WS5, $WS5, $WDUNST "$WS5"
$BIND $MOD+$SHFT+6 $MVTO $WS6, $WS6, $WDUNST "$WS6"
$BIND $MOD+$SHFT+7 $MVTO $WS7, $WS7, $WDUNST "$WS7"
$BIND $MOD+$SHFT+8 $MVTO $WS8, $WS8, $WDUNST "$WS8"
$BIND $MOD+$SHFT+9 $MVTO $WS9, $WS9, $WDUNST "$WS9"
$BIND $MOD+$SHFT+0 $MVTO $WS10, $WS10, $WDUNST "$WS10"

$BIND $MOD+$SHFT+Mod2+KP_1 $MVTO $WS1, $WS1, $WDUNST "$WS1"
$BIND $MOD+$SHFT+Mod2+KP_2 $MVTO $WS2, $WS2, $WDUNST "$WS2"
$BIND $MOD+$SHFT+Mod2+KP_3 $MVTO $WS3, $WS3, $WDUNST "$WS3"
$BIND $MOD+$SHFT+Mod2+KP_4 $MVTO $WS4, $WS4, $WDUNST "$WS4"
$BIND $MOD+$SHFT+Mod2+KP_5 $MVTO $WS5, $WS5, $WDUNST "$WS5"
$BIND $MOD+$SHFT+Mod2+KP_6 $MVTO $WS6, $WS6, $WDUNST "$WS6"
$BIND $MOD+$SHFT+Mod2+KP_7 $MVTO $WS7, $WS7, $WDUNST "$WS7"
$BIND $MOD+$SHFT+Mod2+KP_8 $MVTO $WS8, $WS8, $WDUNST "$WS8"
$BIND $MOD+$SHFT+Mod2+KP_9 $MVTO $WS9, $WS9, $WDUNST "$WS9"
$BIND $MOD+$SHFT+Mod2+KP_0 $MVTO $WS10, $WS10, $WDUNST "$WS10"
$BIND $MOD+$SHFT+Mod2+KP_Divide $MVTO $WS11, $WS11, $WDUNST "$WS11"
$BIND $MOD+$SHFT+Mod2+KP_Multiply $MVTO $WS12, $WS12, $WDUNST "$WS12"

$BIND $MOD+$SHFT+Mod2+KP_End $MVTO $WS1, $WS1, $WDUNST "$WS1"
$BIND $MOD+$SHFT+Mod2+KP_Down $MVTO $WS2, $WS2, $WDUNST "$WS2"
$BIND $MOD+$SHFT+Mod2+KP_Next $MVTO $WS3, $WS3, $WDUNST "$WS3"
$BIND $MOD+$SHFT+Mod2+KP_Left $MVTO $WS4, $WS4, $WDUNST "$WS4"
$BIND $MOD+$SHFT+Mod2+KP_Begin $MVTO $WS5, $WS5, $WDUNST "$WS5"
$BIND $MOD+$SHFT+Mod2+KP_Right $MVTO $WS6, $WS6, $WDUNST "$WS6"
$BIND $MOD+$SHFT+Mod2+KP_Home $MVTO $WS7, $WS7, $WDUNST "$WS7"
$BIND $MOD+$SHFT+Mod2+KP_Up $MVTO $WS8, $WS8, $WDUNST "$WS8"
$BIND $MOD+$SHFT+Mod2+KP_Prior $MVTO $WS9, $WS9, $WDUNST "$WS9"
$BIND $MOD+$SHFT+Mod2+KP_Insert $MVTO $WS10, $WS10, $WDUNST "$WS11"
#$BIND $MOD+$SHFT+Mod2+KP_Delete $MVTO $WS11, $WS11, $WDUNST "$WS12"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # WINDOW MANAGER COMMAND KEYS # # # # # # # # # # # # #
floating_modifier $MOD
tiling_drag modifier titlebar
set $CHILD i3-msg focus child
$BIND $MOD+a $EXC i3-msg focus parent \
	|| ( $CHILD && $CHILD && $CHILD && $CHILD $CHILD && $CHILD \
	&& $CHILD && $CHILD && $CHILD ) && i3-msg focus parent
$BIND $MOD+$SHFT+r layout toggle splitv splith tabbed
$BIND $MOD+r layout toggle splith tabbed splitv
$BIND $MOD+q kill
$BIND $MOD+z split toggle
$BIND $MOD+g fullscreen toggle
$BIND $MOD+$SHFT+space floating toggle, $RSZ 708 385, $MVC
$BIND $MOD+$ALT+space floating toggle
$BIND $MOD+space focus mode_toggle
$BIND $MOD+$SHFT+x $EXC scratchpad &
$BIND $MOD+x $EXC $MSG "scratchpad show" && $ADUNST "Scratchpad Toggled" &

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # AUTOSTART APPLICATIONS / FLOATING WINDOWS # # # # # # # # # # #
$EXCA dunst &
$EXCA killall i3-auto-layout && i3-auto-layout || i3-auto-layout &
$EXC $BAR main & $BAR work1 & $BAR work3
$EXC tmpfs &
$EXC getspeed &
$EXC getweather &
$EXCA playerctld &
$EXC xfce4-clipman start &
$EXC pipewire &
$EXC pipewire-pulse &
$EXC wireplumber &
$EXC doas-check &
$EXC kdeconnect-anyfm &
$EXC xfce-polkit || $WARN "Error polkit"
$EXC doas zramen make -s 200 -a zstd || $WARN "Error zramen"

$FW [class="^.*"] border 1pixel
$FW [class="^steam$"] $FLOAT
$FW [class="Alacritty" title="Xterminal"] $FLOAT, $RSZ 708 385, $MVC
$FW [class="Mate-calc" instance="mate-calc"] $FLOAT
$FW [class="Catfish" instance="catfish"] $FLOAT
$FW [class="Connman-gtk"] $FLOAT
$FW [class="Baobab"] $FLOAT
$FW [class="ark"] $FLOAT, $RSZ 600 420, $MVC
$FW [class="SpeedCrunch"] $FLOAT, $RSZ 240 360, $MVC
$FW [class="File-roller" instance="file-roller"] $FLOAT
$FW [class="pavucontrol-qt"] $FLOAT, $RSZ 530 340, $MVC
$FW [class="LibreWolf" instance="Places"] $FLOAT
$FW [class="Nitrogen" instance="nitrogen"] $FLOAT
$FW [class="Lxappearance" instance="lxappearance"] $FLOAT
$FW [class="Wrapper-2.0" instance="wrapper-2.0"] $FLOAT
$FW [class="Xfce4-panel" instance="xfce4-panel"] $FLOAT
$FW [class="Zenity" title="Calendar selection"] $FLOAT, \
	$RSZ 290 240, $MVC, move up 317 px, move right 569 px
$FW [class="scrcpy"] $FLOAT, $RSZ 300 650
$FW [instance="origin.exe"] $FLOAT
$FW [instance="eadesktop.exe"] $FLOAT
$FW [instance="eaappinstaller.exe"] $FLOAT
$FW [class="steam"] $MVTO $WS11, $WS11
$FW [class="yuzu"] $MVTO $WS11, $WS11
$FW [class="suyu"] $MVTO $WS11, $WS11
$FW [class="citron"] $MVTO $WS11, $WS11
$FW [class="dolphin-emu"] $MVTO $WS11, $WS11
$FW [class="PPSSPPSDL"] $MVTO $WS11, $WS11
$FW [class="PPSSPPQt"] $MVTO $WS11, $WS11
$FW [class="BeamNG.drive.x64"] $MVTO $WS11, $WS11
$FW [title="File Operation Progress"] $FLOAT, $MVC
$FW [class="Deadbeef" title="^(?i)(?!Track Properties)(?!Spectrum options)\
(?!Waveform Properties)(?!Converter)(?!Preferences).*"] $FLOAT, \
	$RSZ 708 353, $MVC, move up 261 px, move right 360px
$FW [class="Deadbeef" title="^(?i)(?=Preferences|Converter|Waveform Properties\
	|Track Properties|Spectrum options).*"] $FLOAT, $MVC


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # MAIN APPlICATIONS AND MEDIA KEYS  # # # # # # # # # # # # #
set $RX1 i3-msg '[class="Hellium" title="^(?i)(?!.*\bTelegram Web\b)(?!.* Discord)(?!.*\bWhatsApp\b).*"] focus'
$BIND $MOD+F1 $EXC $RX1 && $ADUNST "FireDragon" \
	|| ( helium & $ADUNST "Launching Hellium" )
$BIND $MOD+$SHFT+F1 $EXC helium & $ADUNST "New helium Window"
$BIND $MOD+F2 $EXC thunar &
$BIND $MOD+F3 $EXC getbeef &
$BIND $MOD+F6 $EXC steam &

$BIND $MOD+v $EXC xfce4-clipman popup &
$BIND $MOD+$SHFT+z $EXC xfce4-screenshooter &
$BIND $ALT+Tab $EXC rofi-launch alt-tab &
$BIND $MOD+Tab $EXC rofi-launch alt-tab &
$BIND $MOD+Return $EXC rofi-launch menu &
$BIND $MOD+grave $EXC rofi-launch menu &
$BIND $MOD+o $EXC rofi-launch emoji &
$BIND $MOD+n $EXC dunstctl history-pop &
$BIND $MOD+c $EXC killall speedcrunch || speedcrunch
$BIND $MOD+b $EXC killall pavucontrol-qt || pavucontrol-qt &
$BIND $CTRL+$ALT+t $EXC gettop &
$BIND $MOD+KP_Enter $EXC alacritty --title="Xterminal"
$BIND $MOD+t $EXC alacritty &
$BIND $MOD+$SHFT+q $EXC rofi-launch power-menu
$BIND $CTRL+$ALT+k $EXC xkill &
$BIND $MOD+$ALT+s $EXC getscheduler &

$BIND XF86AudioRaiseVolume $EXC getsound VOL+ &
$BIND XF86AudioLowerVolume $EXC getsound VOL- &
$BIND $SHFT+XF86AudioRaiseVolume $EXC getsound VOL+ --NOLIMIT &
$BIND $SHFT+XF86AudioLowerVolume $EXC getsound VOL- --NOLIMIT &
$BIND XF86AudioMute $EXC getsound TOGGLEMUTE &
$BIND XF86AudioPlay $EXC playerctl play-pause &
$BIND XF86AudioPause $EXC playerctl play-pause &
$BIND XF86AudioNext $EXC playerctl next &
$BIND XF86AudioPrev $EXC playerctl previous &
$BIND XF86AudioStop $EXC playerctl stop &

$BIND $MOD+comma $EXC playerctl previous &
$BIND $MOD+period $EXC playerctl next &
$BIND $MOD+m $EXC getplayer TOGGLEPLAY &
$BIND $MOD+$SHFT+comma $EXC getplayer VOL- &
$BIND $MOD+$SHFT+period $EXC getplayer VOL+ &
$BIND $MOD+$ALT+comma $EXC playerctl position 5- &
$BIND $MOD+$ALT+period $EXC playerctl position 5+ &
$BIND $MOD+$CTRL+comma $EXC getsound VOL- &
$BIND $MOD+$CTRL+period $EXC getsound VOL+ &

$BIND --whole-window $MOD+button2 floating toggle, $RSZ 708 385, $MVC
$BIND --whole-window $MOD+button9 $EXC playerctl next &
$BIND --whole-window $MOD+button8 $EXC playerctl previous &
$BIND --whole-window $MOD+$SHFT+button8 $EXC getplayer TOGGLEPLAY &

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # EDIT I3 / POLYBAR # # # # # # # # # # # # # # # # # #
$BIND $MOD+$ALT+r $EXC $MSG restart &
$BIND $MOD+$ALT+p $EXC $TXTE $CONFIG/$BAR/config.ini &
$BIND $MOD+$ALT+i $EXC $TXTE $CONFIG/i3/config &
$BIND $MOD+$ALT+d $EXC $TXTE $CONFIG/dunst/dunstrc &
