enable_selector = false
selector = "rofi -dmenu -i -p 'Open With: '"
term_exec_args = '-e'

[[handlers]]
exec = "braveapps piped %u" # Uses desktop entry field codes
terminal = false # Set to true for terminal apps, false for GUI apps (optional; defaults to false)
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.'] # Use single-quote literal strings
